# mainline windows build
name: Make CI (MSYS2 for Windows)

on:
  push:
    branches:
      - "**"
  pull_request:
    branches:
      - "**"

jobs:
  build-msys2-windows:
    # windows-latest = windows-2019 => windows-2022
    # https://docs.github.com/ja/actions/using-github-hosted-runners/about-github-hosted-runners
    # https://github.com/actions/virtual-environments/blob/main/images/win/Windows2019-Readme.md
    # https://github.com/actions/virtual-environments/blob/main/images/win/Windows2022-Readme.md
    runs-on: windows-2022

    strategy:
      matrix:
        edition:
          - YANEURAOU_ENGINE_NNUE
        compiler:
          - clang++
        target:
          - tournament
          - gensfen
          - evallearn
        archcpu:
          - SSE42

    steps:
      - name: Checkout own repository
        uses: actions/checkout@v2
        with:
          path: main

      - name: Install pkg
        run: |
          $ErrorActionPreference = 'Continue'
          C:\msys64\usr\bin\bash.exe -lc 'pacman --needed --noconfirm -Syuu'
          C:\msys64\usr\bin\bash.exe -lc 'pacman --needed --noconfirm -Syuu'
          C:\msys64\usr\bin\bash.exe -lc 'pacman --needed --noconfirm -Syuu pactoys'
          C:\msys64\usr\bin\bash.exe -lc 'pacboy --needed --noconfirm -Sy clang:m lld:m openblas:x openmp:x toolchain:m base-devel:'
          $ErrorActionPreference = 'Stop'

      - name: make
        run: |
          $env:PATH+=';C:\msys64';
          .\main\script\msys2_build.ps1 -Edition ${{ matrix.edition }} -Compiler ${{ matrix.compiler }} -Target ${{ matrix.target }} -Cpu ${{ matrix.archcpu }}
        shell: pwsh

      - uses: actions/upload-artifact@v2
        with:
          name: build-windows_${{ github.run_number }}_${{ github.sha }}
          path: ./main/build/**/*
